name: ifnews
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flat_list: ^0.1.14
  page_view_dot_indicator: ^2.1.0
  toast: ^0.3.0
  flutter_share: ^2.0.0
  intl: ^0.19.0
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.17.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/recursos/jsons/feed.json
    - lib/recursos/jsons/comentarios.json
    - lib/recursos/imagens/avatar.png
    - lib/recursos/imagens/cafe.jpeg
    - lib/recursos/imagens/filosofia.jpeg
    - lib/recursos/imagens/iel.jpeg
    - lib/recursos/imagens/ifba1.jpeg
    - lib/recursos/imagens/inclusao.jpeg
    - lib/recursos/imagens/jifba.jpeg
    - lib/recursos/imagens/libras.jpeg
    - lib/recursos/imagens/pesquisa.jpeg
    - lib/recursos/imagens/posgrad.jpeg
    - lib/recursos/imagens/refeitorio.jpeg
    - lib/recursos/imagens/robotica.jpeg
    - lib/recursos/imagens/semanatec.jpeg
    - lib/recursos/imagens/seminario.jpeg
    - lib/recursos/imagens/tesouro.jpeg
    - lib/recursos/imagens/voz.jpeg